services:
  server:
    build:
      context: .
      target: dev
    ports:
      - 5000:5000
      - 9230:9230
    environment:
      - PORT=${PORT}
      - DB_URL=${DB_URL}
    depends_on:
      chat_db:
        condition: service_healthy
    volumes:
      - ./src:/app/src
  chat_db:
    image: mongo
    restart: always
    volumes:
      - chat-db-data:/data/db
    environment:
      MONGO_INITDB_DATABASE: ${DB_NAME}
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - 27017:27017
    expose:
      - 27017
    healthcheck:
      test: ["CMD","mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 20s
  redis:
    container_name: chat_redis
    image: redis
    restart: always
    command: --port 6380
    ports:
      - 6380:6380
    expose:
      - 6380
volumes:
  chat-db-data:
