services:
  server:
    build:
      context: .
      target: dev
    ports:
      - ${PORT}:${PORT}
      - ${DEBUG_PORT}:${DEBUG_PORT}
    environment:
      - PORT:${PORT}
      - DB_URL=${DB_URL}
    volumes:
      - ./src:/app/src
  redis:
    container_name: chat_redis
    image: redis
    restart: always
    command: --port ${STORAGE_PORT}
    ports:
      - ${STORAGE_PORT}:${STORAGE_PORT}
    expose:
      - ${STORAGE_PORT}
volumes:
  chat-db-data:
